Jeevan/Models/RequestInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Jeevan.Models
{
    public class RequestInfo
    {
        [Required]
        [DisplayName("Patient's Name")]
        public string PatientName { get; set; }

        [DisplayName("Patient's Date of birth")]
        [DataType(DataType.Date)]
        public DateTime PatientDateOfBirth { get; set; }

        [Required,UIHint("_Gender")]
        [DisplayName("Patient's Gender")]
        public string Gender { get; set; }

        public string Hospital { get; set; }
        [DisplayName("Physician's Name"),Required]
        public string PhysicianName { get; set; }

        [DisplayName("Physician's email address"),Required]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Please Enter a valid Email")]
        public string PhysicianEmail { get; set; }

        [DisplayName("Physician's phone number")]
        [RegularExpression(@"^[+]{0,1}\d+$", ErrorMessage = "Enter a valid phone number")]
        public string PhysicanPhoneNumber { get; set; }

        public string Diagnosis { get; set; }
    }
}

Jeevan/Models/ViewModels/RequestInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Jeevan.Models.ViewModels
{
    public class RequestInfoViewModel
    {
        public PatientInfo PatientInfo { get; set; }
        public CordBloodUnit HLAType { get; set; }
    }
}

Jeevan/Controllers/RequestInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jeevan.Database;
using Jeevan.Models;
using Jeevan.Models.ViewModels;
using Mvc.Mailer;

namespace Jeevan.Controllers
{
    public class RequestInfoController : Controller
    {
        //
        // GET: /Default1/
        private JeevanDBContext db = new JeevanDBContext();

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Default1/Create

        public ActionResult Create()
        {
            return View();
        }

        public ViewResult Success()
        {
            return View();
        }

        //
        // GET: /RequestInfo/HLAMatches

        public ActionResult HLAMatches(PatientInfo info, CordBloodUnit cordBloodUnit)
        {
            try
            {
                var searchResults = db.CordBloodUnits.Select(c => c)
                                                   .Where(unit =>
                                                             unit.DRB_1 == cordBloodUnit.DRB_1
                                                          && unit.DRB_2 == cordBloodUnit.DRB_2
                                                          &&( 
                                                              (cordBloodUnit.HLA_A1.HasValue ? unit.HLA_A1 == cordBloodUnit.HLA_A1 : true)
                                                              || (cordBloodUnit.HLA_A2.HasValue ? unit.HLA_A2 == cordBloodUnit.HLA_A2 : true)
                                                              || (cordBloodUnit.HLA_B1.HasValue ? unit.HLA_B1 == cordBloodUnit.HLA_B1 : true)
                                                              || (cordBloodUnit.HLA_B2.HasValue ? unit.HLA_B2 == cordBloodUnit.HLA_B2 : true)
                                                            )
                                                          ).ToList();

                var model = new HLASearchResultsViewModel() { _5Matches = searchResults.Where(x => x.GetMatchCount(cordBloodUnit) == 5), _6Matches = searchResults.Where(x => x.GetMatchCount(cordBloodUnit) == 6) };

                return PartialView("_SearchResults", model);
            }
            catch
            {
                return View();
            }
        }

        

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        private UserMailer _mailer = new UserMailer();

        public UserMailer Mailer
        {
            get { return _mailer; }
            set { _mailer = value; }
        }

        
        public ActionResult SendMail(PatientInfo requestInfo, CordBloodUnit cordBloodUnit)
        {
            var viewModel = new RequestInfoViewModel() { PatientInfo = requestInfo, HLAType = cordBloodUnit };
            Mailer.Welcome(viewModel).Send();
            return new EmptyResult();
        }
    }
}

Jeevan/Views/RequestInfo/ConfirmRequest.cshtml
@{
    ViewBag.Title = "ConfirmRequest";
}

<h3>Matching Samples found</h3>

@foreach (var group in ViewBag.Results)
{ 
    <strong>group.Count</strong><br />
    
    foreach (var sample in group.Samples)
    {
        <div>sample.DRB_1</div>
    }
}

Jeevan/Views/RequestInfo/Create.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Ajax.BeginForm("HLAMatches",
                new AjaxOptions()
                {
                    HttpMethod = "GET",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "hlaSearchResults"
                }))
{
    #region models
    var requestInfo = new Jeevan.Models.PatientInfo()
            {
                Diagnosis = "cancer",
                Gender = "Male",
                Hospital = "Apollo",
                PatientName = "xyz",
                PhysicanPhoneNumber = "9841012345",
                PhysicianEmail = "house@apollo.com",
                PhysicianName = "dr. House"
            };
    var HLA_type = new Jeevan.Models.CordBloodUnit() { HLA_A1 = 2, HLA_A2 = 24, HLA_B1 = 18, HLA_B2 = 40, DRB_1 = 11, DRB_2 = 14 };
    #endregion 
            <div id="patientInfo">
            @Html.Partial("_RequestInfoPatient")
        </div>
    <div>
        <br />

        <h3>Patient's HLA Type</h3>
    </div>
        <div id="hlaInfo">
            @Html.Partial("_Search")
        </div>
        <br /><br />
            <div>
                <input type="submit" name="proceed" value="Proceed" />
                <input type="reset" name="cancel" value="Clear" />
            </div>
        }
<div id="hlaSearchResults">
</div>
<script type="text/javascript">
    $(function () {
        $("#search").hide();
        $("#DateOfBirth").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "1950:2013",
            maxDate: 0
        });
    });

</script>

Jeevan/Views/RequestInfo/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2> :-) Success</h2>

<p class="lead">
    We have received your request. We shall get back to you as quick as possible. 
</p>

Jeevan/Views/RequestInfo/_RequestInfoPatient.cshtml
@model Jeevan.Models.PatientInfo

<fieldset>
    <legend><h3>Patient information</h3></legend>
    @Html.EditorForModel()
    
</fieldset>

Jeevan/Views/RequestInfo/_Search.cshtml
@model Jeevan.Models.CordBloodUnit

<style>
    label {
        margin-top: 5px;
    }
</style>
@Html.ValidationSummary()<br />
<div class="row">
<div class="span1"><label> A1 </label></div>
<div class="span2">@Html.TextBoxFor(cb => cb.HLA_A1, new{placeholder = " A1 ", @class = "HLASearchBox"}) </div>
<div class="span1"><label> A2 </label></div>
<div class="span2">@Html.TextBoxFor(cb => cb.HLA_A2, new{placeholder = " A2 ", @class = "HLASearchBox"})</div>
</div>
<div class="row">
<div class="span1"><label> B1 </label></div>
<div class="span2">@Html.TextBoxFor(cb => cb.HLA_B1, new{placeholder = " B1 ", @class = "HLASearchBox"})</div>
<div class="span1"><label> B2 </label></div>
<div class="span2">@Html.TextBoxFor(cb => cb.HLA_B2, new{placeholder = " B2 ", @class = "HLASearchBox"})</div>
</div>
<div class="row">
<div class="span1"><label> DRB 1a </label></div>
<div class="span2">@Html.TextBoxFor(cb => cb.DRB_1, new{placeholder = " DRB 1a ", @class = "HLASearchBox"})</div>
<div class="span1"><label> DRB 1b </label></div>
<div class="span2">@Html.TextBoxFor(cb => cb.DRB_2, new{placeholder = " DRB 1b ", @class = "HLASearchBox"})</div>
</div>

Jeevan/Views/RequestInfo/_SearchResults.cshtml
@model Jeevan.Models.ViewModels.HLASearchResultsViewModel
<div id="hlaSearchResults">
   
    
    @if (Model._5Matches.Any() || Model._6Matches.Any())
    {
        <h3>6/6 Matches</h3>
         <table class="table table-striped table-bordered">
            <thead>            <tr>                <td>                    ID                </td>                <td>                    HLA A1                </td>                <td>                    HLA A2                </td>                <td>                    HLA B1                </td>                <td>                    HLA B2                </td>                <td>                    DRB 1                </td>                <td>                    DRB 2                </td>            </tr>        </thead>   
            <tbody>
            @foreach (var unit in Model._6Matches)
            { 
                <tr>
                    <td>
                        @unit.ID
                    </td>
                    <td>
                        @unit.HLA_A1
                    </td>
                    <td>
                        @unit.HLA_A2
                    </td>
                    <td>
                        @unit.HLA_B1
                    </td>
                    <td>
                        @unit.HLA_B2
                    </td>
                    <td>
                        @unit.DRB_1
                    </td>
                    <td>
                        @unit.DRB_2
                    </td>
                </tr>
            }
            </tbody>
      </table>
    <h3>5/6 Matches</h3>
    <table class="table table-striped table-bordered">
        <thead>            <tr>                <td>                    ID                </td>                <td>                    HLA A1                </td>                <td>                    HLA A2                </td>                <td>                    HLA B1                </td>                <td>                    HLA B2                </td>                <td>                    DRB 1                </td>                <td>                    DRB 2                </td>           </tr>        </thead>   
        <tbody>
        @foreach (var unit in Model._5Matches)
        { 
            <tr>
                <td>
                    @unit.ID
                </td>
                <td>
                    @unit.HLA_A1
                </td>
                <td>
                    @unit.HLA_A2
                </td>
                <td>
                    @unit.HLA_B1
                </td>
                <td>
                    @unit.HLA_B2
                </td>
                <td>
                    @unit.DRB_1
                </td>
                <td>
                    @unit.DRB_2
                </td>
            </tr>
        }
        </tbody>
       </table>
        <button class="btn btn-success" id="sendEmail"> make a request </button>
    }
    else
    {
    <p><h3>Sorry :-( , No Matches found</h3></p>
    }
    
</div>
<script type="text/javascript">
    $("#sendEmail.btn").click(function () {
        var formData = $("form").serialize();
        $.ajax({
            data: formData,
            url: '@Url.Action("SendMail", "RequestInfo")',
            method: 'GET'
        }).success(function () {
            window.location='@Url.Action("Success", "RequestInfo")';
        }
        
        );
    });
</script>